//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationControl
    {
        public int recid { get; set; }
        public string version { get; set; }
        public string comment { get; set; }
        public bool required { get; set; }
        public System.DateTime storeDate { get; set; }
        public System.DateTime createdDate { get; set; }
        public string devicePlatform { get; set; }
        public bool published { get; set; }
    }
}
