//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Log_SmsBildirimleri
    {
        public int recid { get; set; }
        public string telefon { get; set; }
        public string sms_text { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
