//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Log_Errors
    {
        public int recid { get; set; }
        public string process { get; set; }
        public string method { get; set; }
        public string parameters { get; set; }
        public string errorMessage { get; set; }
        public string platform { get; set; }
        public string device { get; set; }
        public System.DateTime createdDate { get; set; }
    }
}
