//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Log_UserLocal
    {
        public int userRecid { get; set; }
        public string client_ip { get; set; }
        public string client_port { get; set; }
        public string client_browser { get; set; }
        public string client_language { get; set; }
        public Nullable<bool> isMobile { get; set; }
        public string client_system { get; set; }
        public Nullable<System.DateTime> date_utc { get; set; }
        public long recid { get; set; }
    }
}
