//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultOdemeler
    {
        public int recid { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public Nullable<decimal> odenen { get; set; }
        public string anlasmaOzeti { get; set; }
        public Nullable<System.DateTime> baslangicTarihi { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
