//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultAskTestiCevapAciklama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public defaultAskTestiCevapAciklama()
        {
            this.defaultUserAsk = new HashSet<defaultUserAsk>();
            this.defaultUserAsk1 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk2 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk3 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk4 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk5 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk6 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk7 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk8 = new HashSet<defaultUserAsk>();
            this.defaultUserAsk9 = new HashSet<defaultUserAsk>();
        }
    
        public byte cevapRecid { get; set; }
        public string cevapAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultUserAsk> defaultUserAsk9 { get; set; }
    }
}
