//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultHavale
    {
        public short recid { get; set; }
        public int userRecid { get; set; }
        public string adSoyad { get; set; }
        public string e_posta { get; set; }
        public string telefon { get; set; }
        public byte paketRecid { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> sil { get; set; }
    
        public virtual usersDetail usersDetail { get; set; }
        public virtual uyelikTurPaket uyelikTurPaket { get; set; }
    }
}
