//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultContact
    {
        public int recid { get; set; }
        public Nullable<int> userRecid { get; set; }
        public string adSoyad { get; set; }
        public string e_posta { get; set; }
        public string telefon { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }
        public string ip_adres { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<short> tip { get; set; }
        public Nullable<bool> sil { get; set; }
        public string device { get; set; }
    }
}
