//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultUserAsk
    {
        public int userRecid { get; set; }
        public Nullable<byte> s1c { get; set; }
        public Nullable<byte> s2c { get; set; }
        public Nullable<byte> s3c { get; set; }
        public Nullable<byte> s4c { get; set; }
        public Nullable<byte> s5c { get; set; }
        public Nullable<byte> s6c { get; set; }
        public Nullable<byte> s7c { get; set; }
        public Nullable<byte> s8c { get; set; }
        public Nullable<byte> s9c { get; set; }
        public Nullable<byte> s10c { get; set; }
    
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama1 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama2 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama3 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama4 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama5 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama6 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama7 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama8 { get; set; }
        public virtual defaultAskTestiCevapAciklama defaultAskTestiCevapAciklama9 { get; set; }
        public virtual defaultUserAsk defaultUserAsk1 { get; set; }
        public virtual defaultUserAsk defaultUserAsk2 { get; set; }
    }
}
