//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultAskTestiCevaplar
    {
        public byte recid { get; set; }
        public Nullable<byte> soruRecid { get; set; }
        public string cevap { get; set; }
    
        public virtual defaultAskTestiSorular defaultAskTestiSorular { get; set; }
    }
}
