//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultIliskiDanismani
    {
        public int recid { get; set; }
        public int userRecid { get; set; }
        public string soru { get; set; }
        public string cevap { get; set; }
        public Nullable<System.DateTime> sorulanTarih { get; set; }
        public Nullable<System.DateTime> cevapTarih { get; set; }
        public Nullable<bool> sil { get; set; }
        public string iletisim { get; set; }
        public string baslik { get; set; }
    }
}
