//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class duvarCanli
    {
        public int recid { get; set; }
        public int userRecid { get; set; }
        public string detay { get; set; }
        public System.DateTime tarih { get; set; }
        public short durum { get; set; }
        public Nullable<bool> profilOnay { get; set; }
        public string routeBaslik { get; set; }
        public Nullable<int> begen { get; set; }
        public short tip { get; set; }
    
        public virtual usersDetail usersDetail { get; set; }
    }
}
