//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class duvarCanliBegenenler
    {
        public int recid { get; set; }
        public int begenenId { get; set; }
        public System.DateTime tarih { get; set; }
        public int duvarId { get; set; }
        public int paylasanId { get; set; }
    
        public virtual usersDetail usersDetail { get; set; }
        public virtual usersDetail usersDetail1 { get; set; }
    }
}
