//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class goldManuel
    {
        public int recid { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> userRecid { get; set; }
        public string hareketOturumID { get; set; }
        public Nullable<byte> paketRecid { get; set; }
        public string aciklama { get; set; }
        public string userMaxID { get; set; }
    }
}
