//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class goldHediye
    {
        public int userRecid { get; set; }
        public System.DateTime tarih { get; set; }
        public short kalan { get; set; }
        public Nullable<bool> fake { get; set; }
        public byte paketRecid { get; set; }
    
        public virtual usersDetail usersDetail { get; set; }
        public virtual uyelikTurPaket uyelikTurPaket { get; set; }
    }
}
