//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class goldHareket
    {
        public int recid { get; set; }
        public int userRecid { get; set; }
        public byte islemAdimi { get; set; }
        public byte paketID { get; set; }
        public Nullable<short> odemeSekli { get; set; }
        public Nullable<bool> sonuc { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string oturumID { get; set; }
        public Nullable<short> uyeTipID { get; set; }
        public string paySuit_Code { get; set; }
        public Nullable<short> paySuit_Sonuc { get; set; }
        public string paySuit_Url_buy { get; set; }
        public string paySuit_Url_check { get; set; }
        public string micro_object_id { get; set; }
    
        public virtual usersDetail usersDetail { get; set; }
    }
}
