//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class gtt
    {
        public int recid { get; set; }
        public System.DateTime tarih { get; set; }
        public byte tahakkukTipi { get; set; }
        public decimal tutar { get; set; }
        public int userID { get; set; }
        public byte kullaniciUserMax { get; set; }
    }
}
