//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemHediye
    {
        public int recid { get; set; }
        public int gonderen { get; set; }
        public int alici { get; set; }
        public System.DateTime gonderimTarihi { get; set; }
        public int hediyeRecid { get; set; }
        public Nullable<int> gizle { get; set; }
        public Nullable<bool> sil { get; set; }
    
        public virtual islemHediyeler islemHediyeler { get; set; }
    }
}
