//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemResimGoster
    {
        public int recid { get; set; }
        public int kullanici { get; set; }
        public int gosterilecekKisi { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<int> gizle { get; set; }
        public Nullable<bool> sil { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
