//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeHub.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemResimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public islemResimler()
        {
            this.usersDetail = new HashSet<usersDetail>();
        }
    
        public int recid { get; set; }
        public string resim { get; set; }
        public int kullanici { get; set; }
        public Nullable<System.DateTime> yuklenmeTarihi { get; set; }
        public bool goster { get; set; }
        public byte onay { get; set; }
        public string gosterTxt { get; set; }
        public string rotate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usersDetail> usersDetail { get; set; }
    }
}
