//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemFavori
    {
        public int recid { get; set; }
        public int ekleyen { get; set; }
        public int eklenen { get; set; }
        public System.DateTime eklemeTarihi { get; set; }
        public Nullable<int> gizle { get; set; }
        public Nullable<bool> sil { get; set; }
        public Nullable<bool> sms_case { get; set; }
        public Nullable<System.DateTime> sms_gonderim_tarihi { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
