//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class islemMesaj
    {
        public int recid { get; set; }
        public int gonderen { get; set; }
        public int alici { get; set; }
        public string mesaj { get; set; }
        public System.DateTime tarih { get; set; }
        public bool okundu { get; set; }
        public string mesajLeft { get; set; }
        public int visible { get; set; }
        public bool sil { get; set; }
        public Nullable<bool> sms_case { get; set; }
    }
}
