//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_userLogin
    {
        public int recid { get; set; }
        public Nullable<int> userRecid { get; set; }
        public string ip_Adress { get; set; }
        public string browser { get; set; }
        public string isletimSistemi { get; set; }
        public string port { get; set; }
        public string dil { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string ekran { get; set; }
    }
}
