//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.HubAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public System.Guid recid { get; set; }
        public string clientRecevierId { get; set; }
        public int receiverUserID { get; set; }
        public int senderUserID { get; set; }
        public string message { get; set; }
        public int visibleUserID { get; set; }
        public bool seen { get; set; }
        public bool isMobile { get; set; }
        public string language { get; set; }
        public bool temporaryMessage { get; set; }
        public bool isImage { get; set; }
        public string senderProfileImage { get; set; }
        public bool timeOut { get; set; }
        public System.DateTime createdDate { get; set; }
    }
}
