//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class signedAgremeents
    {
        public int recid { get; set; }
        public Nullable<int> userRecid { get; set; }
        public string orderObjectId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<int> mPay { get; set; }
        public Nullable<int> agreementType { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
