//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class soruIlgiAlanlari
    {
        public byte recid { get; set; }
        public string tanim { get; set; }
        public Nullable<byte> value { get; set; }
        public string dil { get; set; }
    }
}
